-- ============================================================
--  Correspondencia | Mayola Gaona — Esquema de base de datos
--  Ejecutar en: Supabase Dashboard → SQL Editor → New query
-- ============================================================

-- ============================================================
--  TABLAS
-- ============================================================

-- Usuarios del sistema (login personalizado, no Supabase Auth)
create table if not exists public.usuarios (
    id          bigint generated by default as identity primary key,
    usuario     text not null unique,
    contrasena  text not null,
    rol         text not null default 'usuario',  -- 'admin' o 'usuario'
    created_at  timestamptz not null default now()
);

-- Catálogo de personas autorizadas (select en Recibida/Despachada)
create table if not exists public.autorizados (
    id    bigint generated by default as identity primary key,
    nombre text not null
);

-- Catálogo de estatus (select en Despachada)
create table if not exists public.status (
    id      bigint generated by default as identity primary key,
    status  text not null
);

-- Catálogo de tipos (select en Proposiciones)
create table if not exists public.tipo (
    id   bigint generated by default as identity primary key,
    tipo text not null
);

-- Correspondencia Recibida
create table if not exists public.recibida (
    id              bigint generated by default as identity primary key,
    "Fecha_Recibido" date,
    "Remite"        text,
    "Asunto"        text,
    "Recibio"       text,
    fecha_evento   date,
    "HORA"          time,
    "Lugar"         text,
    "TELEFONO"      text,
    "CORREO"        text,
    "PDF-Imagen"    text,   -- JSON array de URLs públicas
    created_at      timestamptz not null default now()
);

-- Correspondencia Despachada
create table if not exists public.despachada (
    id                       bigint generated by default as identity primary key,
    "Fecha"                  date,
    "Elaboro"                text,
    "Dirigido"               text,
    "Asunto"                 text,
    "Estatus"                text,
    "Recibió"                text,
    "Fecha_recepcion"        date,
    "TELEFONO"               text,
    "CORREO"                 text,
    "Archivos y multimedia"  text,   -- JSON array de URLs públicas
    created_at               timestamptz not null default now()
);

-- Iniciativas
create table if not exists public.iniciativas (
    id                              bigint generated by default as identity primary key,
    fecha_oficio                    date,
    fecha_presentacion_oficialia    date,
    texto                           text,
    comision                        text,
    fecha_turno_legis               date,
    fecha_pleno                     date,
    dictaminada_favor_contra        text,
    decreto                        text,
    objeto                          text,
    pdf                             text,   -- JSON array de URLs públicas
    opinion_consultoria             text,   -- JSON array
    proyecto_dictamen               text,   -- JSON array
    proyecto_decreto                text,   -- JSON array
    created_at                      timestamptz not null default now()
);

-- Proposiciones
create table if not exists public.proposiciones (
    id                                  bigint generated by default as identity primary key,
    fecha_ingreso_procepar              date,
    fecha_pleno                         date,
    proposicion                         text,
    resultado_votacion                  text,
    fecha_acuse_recibido_autoridad      date,
    fecha_respuesta_autoridad           date,
    tipo                                text,
    objetivo                            text,
    turnado_comision                    text,
    acuerdo                             text,   -- JSON array
    respuesta_acuerdo                   text,   -- JSON array
    anotaciones                         text,
    pdf_foto                            text,   -- JSON array
    created_at                          timestamptz not null default now()
);

-- Fiscalización (tabla "fisca")
create table if not exists public.fisca (
    id            bigint generated by default as identity primary key,
    ano           text,
    fecha_sesion  date,
    dictamen_no   text,
    dependencia   text,
    observaciones text,
    dictamen      text,
    voto_diputada text,
    voto_final    text,
    fallo         text,
    created_at    timestamptz not null default now()
);

-- ============================================================
--  RLS  (políticas permisivas para el rol anon/anónimo,
--  ya que la app usa la publishable key desde el navegador)
-- ============================================================
alter table public.usuarios     enable row level security;
alter table public.autorizados  enable row level security;
alter table public.status       enable row level security;
alter table public.tipo         enable row level security;
alter table public.recibida     enable row level security;
alter table public.despachada   enable row level security;
alter table public.iniciativas  enable row level security;
alter table public.proposiciones enable row level security;
alter table public.fisca        enable row level security;

-- Política única: acceso total para anon y authenticated
create policy "anon full access" on public.usuarios      for all using (true) with check (true);
create policy "anon full access" on public.autorizados   for all using (true) with check (true);
create policy "anon full access" on public.status        for all using (true) with check (true);
create policy "anon full access" on public.tipo          for all using (true) with check (true);
create policy "anon full access" on public.recibida      for all using (true) with check (true);
create policy "anon full access" on public.despachada    for all using (true) with check (true);
create policy "anon full access" on public.iniciativas   for all using (true) with check (true);
create policy "anon full access" on public.proposiciones for all using (true) with check (true);
create policy "anon full access" on public.fisca         for all using (true) with check (true);

-- ============================================================
--  STORAGE — bucket público para archivos adjuntos
-- ============================================================
insert into storage.buckets (id, name, public)
values ('attachments', 'attachments', true)
on conflict (id) do nothing;

-- Política: cualquier usuario puede subir/leer/borrar en attachments
create policy "anon full access attachments" on storage.objects
    for all
    using (bucket_id = 'attachments')
    with check (bucket_id = 'attachments');

-- ============================================================
--  DATOS INICIALES (seed)
-- ============================================================

-- Usuario administrador por defecto  (usuario: admin  /  contraseña: admin123)
insert into public.usuarios (usuario, contrasena, rol)
values ('admin', 'admin123', 'admin')
on conflict (usuario) do nothing;

-- Personas autorizadas de ejemplo
insert into public.autorizados (nombre) values
    ('Mayola Gaona'),
    ('Secretaría Particular'),
    ('Dirección de Correspondencia')
on conflict do nothing;

-- Estatus de ejemplo
insert into public.status (status) values
    ('PENDIENTE'),
    ('EN PROCESO'),
    ('CONTESTADO'),
    ('CANCELADO')
on conflict do nothing;

-- Tipos de ejemplo
insert into public.tipo (tipo) values
    ('PROPOSICIÓN CON PUNTO DE ACUERDO'),
    ('PROPOSICIÓN CON MINUTA'),
    ('PROPOSICIÓN DE URGENCIA')
on conflict do nothing;
